// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsStore.Infrastructure.Data;

#nullable disable

namespace SportsStore.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportsStore.Domain.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            Name = "Bóng đá"
                        },
                        new
                        {
                            CategoryID = 2,
                            Name = "Cờ vua"
                        },
                        new
                        {
                            CategoryID = 3,
                            Name = "Bóng chuyền"
                        });
                });

            modelBuilder.Entity("SportsStoreWebApp.Domain.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ProductID");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            Category = "Bóngđá",
                            Description = "Bóng đá chất lượng cao.",
                            ImageUrl = " / images / football.jpg",
                            Name = "Bóng đá World Cup",
                            Price = 25.00m
                        },
                        new
                        {
                            ProductID = 2,
                            Category = "Cờ vua",
                            Description = "Bộ cờ vua bằng gỗ cao cấp.",
                            ImageUrl = "/images/chess.jpg",
                            Name = "Bộ cờ vua chuyên nghiệp",
                            Price = 75.00m
                        },
                        new
                        {
                            ProductID = 3,
                            Category = "Bóng chuyền",
                            Description = "Bóng chuyền dành cho bãi biển.",
                            ImageUrl = "/images/volleyball.jpg",
                            Name = "Bóng chuyền bãi biển",
                            Price = 15.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
